In [106]:
import pandas as pd
import numpy as np
import csv
import chardet
import ast

In [107]:
def farejar_csv(caminho_arquivo):
    with open(caminho_arquivo, 'rb') as arquivo_binario:
        amostra_bytes = arquivo_binario.read(10000)
        resultado_chardet = chardet.detect(amostra_bytes)
        encoding_descoberto = resultado_chardet['encoding']

    with open(caminho_arquivo, 'r', encoding=encoding_descoberto) as arquivo_texto:
        amostra_texto = arquivo_texto.read(1024)
        farejador = csv.Sniffer()
        separador_descoberto = farejador.sniff(amostra_texto).delimiter

    return encoding_descoberto, separador_descoberto

In [108]:
def extrair_metricas(lista_precos):
    p_min = min(lista_precos)
    p_max = max(lista_precos)
    p_med = round(np.mean(lista_precos), 2)

    return pd.Series([p_min, p_max, p_med])

In [109]:
meu_enc, meu_sep = farejar_csv('vendas_q4_raw.csv')

In [110]:
meu_enc, meu_sep

('utf-8', ';')

In [111]:
dados = pd.read_csv('vendas_q4_raw.csv', sep=meu_sep, encoding=meu_enc)

In [112]:
dados

,id_venda,produto,categoria,preco_venda,custo,margem_bruta,precos_concorrentes,data_venda
0,V-001,Notebook ProMax 15,Eletrônicos,"R$ 4.899,90","R$ 3.200,00","34,7%","[4799.90, 5100.00, 4650.00]",2024-10-05
1,V-002,Cadeira Ergonômica X1,Mobiliário,"R$ 1.249,50","R$ 870,30","30,3%","[1300.00, 1190.00]",2024-10-12
2,V-003,"Monitor UltraWide 34""",Eletrônicos,"R$ 3.150,00","R$ 2.410,00","23,5%","[3200.00, 2999.90, 3100.00]",2024-11-03
3,V-004,Teclado Mecânico RGB,Periféricos,"R$ 459,90","R$ 198,50","56,8%","[470.00, 440.00, 499.90]",2024-11-18
4,V-005,Mesa Ajustável Stand,Mobiliário,"R$ 2.780,00","R$ 1.950,00","29,9%","[2650.00, 2900.00]",2024-11-22
5,V-006,Webcam HD Pro,Periféricos,"R$ 389,00","R$ 215,00","44,7%","[399.90, 370.00, 410.00]",2024-12-01
6,V-007,Notebook ProMax 15,Eletrônicos,"R$ 4.750,00","R$ 3.200,00","32,6%","[4799.90, 5100.00, 4650.00]",2024-12-10
7,V-008,Headset Gamer 7.1,Periféricos,"R$ 699,90","R$ 340,00","51,4%","[720.00, 680.00]",2024-12-15

In [113]:
dados[['preco_venda', 'custo']] = dados[['preco_venda', 'custo']].map(lambda x: x.replace('R$ ', '').replace('.', '').replace(',', '.').strip())

In [114]:
dados[['preco_venda', 'custo']] = dados[['preco_venda', 'custo']].astype(np.float64)

In [115]:
dados

,id_venda,produto,categoria,preco_venda,custo,margem_bruta,precos_concorrentes,data_venda
0,V-001,Notebook ProMax 15,Eletrônicos,4899.9,3200.0,"34,7%","[4799.90, 5100.00, 4650.00]",2024-10-05
1,V-002,Cadeira Ergonômica X1,Mobiliário,1249.5,870.3,"30,3%","[1300.00, 1190.00]",2024-10-12
2,V-003,"Monitor UltraWide 34""",Eletrônicos,3150.0,2410.0,"23,5%","[3200.00, 2999.90, 3100.00]",2024-11-03
3,V-004,Teclado Mecânico RGB,Periféricos,459.9,198.5,"56,8%","[470.00, 440.00, 499.90]",2024-11-18
4,V-005,Mesa Ajustável Stand,Mobiliário,2780.0,1950.0,"29,9%","[2650.00, 2900.00]",2024-11-22
5,V-006,Webcam HD Pro,Periféricos,389.0,215.0,"44,7%","[399.90, 370.00, 410.00]",2024-12-01
6,V-007,Notebook ProMax 15,Eletrônicos,4750.0,3200.0,"32,6%","[4799.90, 5100.00, 4650.00]",2024-12-10
7,V-008,Headset Gamer 7.1,Periféricos,699.9,340.0,"51,4%","[720.00, 680.00]",2024-12-15

In [116]:
dados['margem_bruta'] = dados['margem_bruta'].apply(lambda x: x.replace(',', '.').replace('%', '').strip())

In [117]:
dados['margem_bruta'] = dados['margem_bruta'].astype(np.float64)

In [118]:
dados

,id_venda,produto,categoria,preco_venda,custo,margem_bruta,precos_concorrentes,data_venda
0,V-001,Notebook ProMax 15,Eletrônicos,4899.9,3200.0,34.7,"[4799.90, 5100.00, 4650.00]",2024-10-05
1,V-002,Cadeira Ergonômica X1,Mobiliário,1249.5,870.3,30.3,"[1300.00, 1190.00]",2024-10-12
2,V-003,"Monitor UltraWide 34""",Eletrônicos,3150.0,2410.0,23.5,"[3200.00, 2999.90, 3100.00]",2024-11-03
3,V-004,Teclado Mecânico RGB,Periféricos,459.9,198.5,56.8,"[470.00, 440.00, 499.90]",2024-11-18
4,V-005,Mesa Ajustável Stand,Mobiliário,2780.0,1950.0,29.9,"[2650.00, 2900.00]",2024-11-22
5,V-006,Webcam HD Pro,Periféricos,389.0,215.0,44.7,"[399.90, 370.00, 410.00]",2024-12-01
6,V-007,Notebook ProMax 15,Eletrônicos,4750.0,3200.0,32.6,"[4799.90, 5100.00, 4650.00]",2024-12-10
7,V-008,Headset Gamer 7.1,Periféricos,699.9,340.0,51.4,"[720.00, 680.00]",2024-12-15

In [119]:
dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_venda             8 non-null      str
 1   produto              8 non-null      str
 2   categoria            8 non-null      str
 3   preco_venda          8 non-null      float64
 4   custo                8 non-null      float64
 5   margem_bruta         8 non-null      float64
 6   precos_concorrentes  8 non-null      str
 7   data_venda           8 non-null      str
dtypes: float64(3), str(5)
memory usage: 644.0 bytes

In [120]:
dados['precos_concorrentes'] = dados['precos_concorrentes'].apply(ast.literal_eval)

In [121]:
dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_venda             8 non-null      str
 1   produto              8 non-null      str
 2   categoria            8 non-null      str
 3   preco_venda          8 non-null      float64
 4   custo                8 non-null      float64
 5   margem_bruta         8 non-null      float64
 6   precos_concorrentes  8 non-null      object
 7   data_venda           8 non-null      str
dtypes: float64(3), object(1), str(4)
memory usage: 644.0+ bytes

In [122]:
dados

,id_venda,produto,categoria,preco_venda,custo,margem_bruta,precos_concorrentes,data_venda
0,V-001,Notebook ProMax 15,Eletrônicos,4899.9,3200.0,34.7,"[4799.9, 5100.0, 4650.0]",2024-10-05
1,V-002,Cadeira Ergonômica X1,Mobiliário,1249.5,870.3,30.3,"[1300.0, 1190.0]",2024-10-12
2,V-003,"Monitor UltraWide 34""",Eletrônicos,3150.0,2410.0,23.5,"[3200.0, 2999.9, 3100.0]",2024-11-03
3,V-004,Teclado Mecânico RGB,Periféricos,459.9,198.5,56.8,"[470.0, 440.0, 499.9]",2024-11-18
4,V-005,Mesa Ajustável Stand,Mobiliário,2780.0,1950.0,29.9,"[2650.0, 2900.0]",2024-11-22
5,V-006,Webcam HD Pro,Periféricos,389.0,215.0,44.7,"[399.9, 370.0, 410.0]",2024-12-01
6,V-007,Notebook ProMax 15,Eletrônicos,4750.0,3200.0,32.6,"[4799.9, 5100.0, 4650.0]",2024-12-10
7,V-008,Headset Gamer 7.1,Periféricos,699.9,340.0,51.4,"[720.0, 680.0]",2024-12-15

In [123]:
dados[['preco_concorrente_min', 'preco_concorrente_max', 'preco_concorrente_medio']] = dados['precos_concorrentes'].apply(extrair_metricas)

In [124]:
dados

,id_venda,produto,categoria,preco_venda,custo,margem_bruta,precos_concorrentes,data_venda,preco_concorrente_min,preco_concorrente_max,preco_concorrente_medio
0,V-001,Notebook ProMax 15,Eletrônicos,4899.9,3200.0,34.7,"[4799.9, 5100.0, 4650.0]",2024-10-05,4650.0,5100.0,4849.97
1,V-002,Cadeira Ergonômica X1,Mobiliário,1249.5,870.3,30.3,"[1300.0, 1190.0]",2024-10-12,1190.0,1300.0,1245.00
2,V-003,"Monitor UltraWide 34""",Eletrônicos,3150.0,2410.0,23.5,"[3200.0, 2999.9, 3100.0]",2024-11-03,2999.9,3200.0,3099.97
3,V-004,Teclado Mecânico RGB,Periféricos,459.9,198.5,56.8,"[470.0, 440.0, 499.9]",2024-11-18,440.0,499.9,469.97
4,V-005,Mesa Ajustável Stand,Mobiliário,2780.0,1950.0,29.9,"[2650.0, 2900.0]",2024-11-22,2650.0,2900.0,2775.00
5,V-006,Webcam HD Pro,Periféricos,389.0,215.0,44.7,"[399.9, 370.0, 410.0]",2024-12-01,370.0,410.0,393.30
6,V-007,Notebook ProMax 15,Eletrônicos,4750.0,3200.0,32.6,"[4799.9, 5100.0, 4650.0]",2024-12-10,4650.0,5100.0,4849.97
7,V-008,Headset Gamer 7.1,Periféricos,699.9,340.0,51.4,"[720.0, 680.0]",2024-12-15,680.0,720.0,700.00

In [125]:
dados.drop('precos_concorrentes', axis=1, inplace=True)

In [126]:
dados

,id_venda,produto,categoria,preco_venda,custo,margem_bruta,data_venda,preco_concorrente_min,preco_concorrente_max,preco_concorrente_medio
0,V-001,Notebook ProMax 15,Eletrônicos,4899.9,3200.0,34.7,2024-10-05,4650.0,5100.0,4849.97
1,V-002,Cadeira Ergonômica X1,Mobiliário,1249.5,870.3,30.3,2024-10-12,1190.0,1300.0,1245.00
2,V-003,"Monitor UltraWide 34""",Eletrônicos,3150.0,2410.0,23.5,2024-11-03,2999.9,3200.0,3099.97
3,V-004,Teclado Mecânico RGB,Periféricos,459.9,198.5,56.8,2024-11-18,440.0,499.9,469.97
4,V-005,Mesa Ajustável Stand,Mobiliário,2780.0,1950.0,29.9,2024-11-22,2650.0,2900.0,2775.00
5,V-006,Webcam HD Pro,Periféricos,389.0,215.0,44.7,2024-12-01,370.0,410.0,393.30
6,V-007,Notebook ProMax 15,Eletrônicos,4750.0,3200.0,32.6,2024-12-10,4650.0,5100.0,4849.97
7,V-008,Headset Gamer 7.1,Periféricos,699.9,340.0,51.4,2024-12-15,680.0,720.0,700.00

In [127]:
condicoes = [
    (dados['preco_venda'] < dados['preco_concorrente_medio']),
    (dados['preco_venda'] > dados['preco_concorrente_medio'])
]

In [128]:
escolhas = ['abaixo', 'acima']

In [129]:
dados['posicao_mercado'] = np.select(condicoes, escolhas, default='alinhado')

In [130]:
dados

,id_venda,produto,categoria,preco_venda,custo,margem_bruta,data_venda,preco_concorrente_min,preco_concorrente_max,preco_concorrente_medio,posicao_mercado
0,V-001,Notebook ProMax 15,Eletrônicos,4899.9,3200.0,34.7,2024-10-05,4650.0,5100.0,4849.97,acima
1,V-002,Cadeira Ergonômica X1,Mobiliário,1249.5,870.3,30.3,2024-10-12,1190.0,1300.0,1245.00,acima
2,V-003,"Monitor UltraWide 34""",Eletrônicos,3150.0,2410.0,23.5,2024-11-03,2999.9,3200.0,3099.97,acima
3,V-004,Teclado Mecânico RGB,Periféricos,459.9,198.5,56.8,2024-11-18,440.0,499.9,469.97,abaixo
4,V-005,Mesa Ajustável Stand,Mobiliário,2780.0,1950.0,29.9,2024-11-22,2650.0,2900.0,2775.00,acima
5,V-006,Webcam HD Pro,Periféricos,389.0,215.0,44.7,2024-12-01,370.0,410.0,393.30,abaixo
6,V-007,Notebook ProMax 15,Eletrônicos,4750.0,3200.0,32.6,2024-12-10,4650.0,5100.0,4849.97,abaixo
7,V-008,Headset Gamer 7.1,Periféricos,699.9,340.0,51.4,2024-12-15,680.0,720.0,700.00,abaixo

In [131]:
dados['data_venda'] = pd.to_datetime(dados['data_venda'], format='%Y-%m-%d')

In [132]:
dados

,id_venda,produto,categoria,preco_venda,custo,margem_bruta,data_venda,preco_concorrente_min,preco_concorrente_max,preco_concorrente_medio,posicao_mercado
0,V-001,Notebook ProMax 15,Eletrônicos,4899.9,3200.0,34.7,2024-10-05,4650.0,5100.0,4849.97,acima
1,V-002,Cadeira Ergonômica X1,Mobiliário,1249.5,870.3,30.3,2024-10-12,1190.0,1300.0,1245.00,acima
2,V-003,"Monitor UltraWide 34""",Eletrônicos,3150.0,2410.0,23.5,2024-11-03,2999.9,3200.0,3099.97,acima
3,V-004,Teclado Mecânico RGB,Periféricos,459.9,198.5,56.8,2024-11-18,440.0,499.9,469.97,abaixo
4,V-005,Mesa Ajustável Stand,Mobiliário,2780.0,1950.0,29.9,2024-11-22,2650.0,2900.0,2775.00,acima
5,V-006,Webcam HD Pro,Periféricos,389.0,215.0,44.7,2024-12-01,370.0,410.0,393.30,abaixo
6,V-007,Notebook ProMax 15,Eletrônicos,4750.0,3200.0,32.6,2024-12-10,4650.0,5100.0,4849.97,abaixo
7,V-008,Headset Gamer 7.1,Periféricos,699.9,340.0,51.4,2024-12-15,680.0,720.0,700.00,abaixo

In [133]:
dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id_venda                 8 non-null      str
 1   produto                  8 non-null      str
 2   categoria                8 non-null      str
 3   preco_venda              8 non-null      float64
 4   custo                    8 non-null      float64
 5   margem_bruta             8 non-null      float64
 6   data_venda               8 non-null      datetime64[us]
 7   preco_concorrente_min    8 non-null      float64
 8   preco_concorrente_max    8 non-null      float64
 9   preco_concorrente_medio  8 non-null      float64
 10  posicao_mercado          8 non-null      str
dtypes: datetime64[us](1), float64(6), str(4)
memory usage: 836.0 bytes

In [134]:
dados.to_csv('vendas_q4_tratado.csv', sep=';', index=False, encoding='utf-8')