In [208]:
import pandas as pd

### Leitura do arquivo csv

In [209]:
relatorio_operacional_logistica = pd.read_csv('entregas_legado.csv', sep=';', encoding='utf-8')

In [210]:
relatorio_operacional_logistica

,id_entrega,cliente,rota,data_pedido,data_entrega,tempo_transporte,peso_kg,valor_frete,status_entrega
0,E-001,MAGAZINE CENTRAL LTDA,São Paulo/SP -> Curitiba/PR,15/03/2024,2024-03-18,3 dias e 4 horas,"1250,5","R$ 3.890,00",ENTREGUE - sem ocorrências
1,E-002,TECH STORE ME,Rio de Janeiro/RJ -> Belo Horizonte/MG,2024/04/02,05-04-2024,2 dias e 18 horas,"780,0","R$ 2.150,75",ENTREGUE - com atraso de 6h
2,E-003,Distribuidora Nordeste S.A.,Recife/PE -> Salvador/BA,28/04/2024,2024-05-01,2 dias e 12 horas,"2100,8","R$ 5.420,00",ENTREGUE - sem ocorrências
3,E-004,AUTO PEÇAS REGIONAL LTDA,Manaus/AM -> Belém/PA,2024/05/10,15-05-2024,4 dias e 22 horas,"3500,0","R$ 12.750,30",ENTREGUE - com avaria parcial
4,E-005,pharma express distribuidora,Curitiba/PR -> Florianópolis/SC,20/06/2024,2024-06-21,1 dia e 8 horas,"420,3","R$ 1.280,00",ENTREGUE - sem ocorrências
5,E-006,MEGA ATACADO EIRELI,Porto Alegre/RS -> São Paulo/SP,2024/07/15,19-07-2024,3 dias e 16 horas,"1890,0","R$ 4.670,50",ENTREGUE - com atraso de 12h
6,E-007,Casa & Construção Materiais,Brasília/DF -> Goiânia/GO,01/08/2024,2024-08-02,1 dia e 14 horas,"960,7","R$ 1.950,00",ENTREGUE - sem ocorrências

### Tokenização da coluna 'rota'

In [211]:
relatorio_operacional_logistica['rota']

0               São Paulo/SP -> Curitiba/PR
1    Rio de Janeiro/RJ -> Belo Horizonte/MG
2                  Recife/PE -> Salvador/BA
3                     Manaus/AM -> Belém/PA
4           Curitiba/PR -> Florianópolis/SC
5           Porto Alegre/RS -> São Paulo/SP
6                 Brasília/DF -> Goiânia/GO
Name: rota, dtype: str

In [212]:
relatorio_operacional_logistica['rota'] = (relatorio_operacional_logistica['rota']
 .str.replace(r"/", ',', regex=True)
 .str.replace(r"\s*->\s*", ',', regex=True)
 .str.strip()
 .str.split(','))

In [213]:
relatorio_operacional_logistica

,id_entrega,cliente,rota,data_pedido,data_entrega,tempo_transporte,peso_kg,valor_frete,status_entrega
0,E-001,MAGAZINE CENTRAL LTDA,"[São Paulo, SP, Curitiba, PR]",15/03/2024,2024-03-18,3 dias e 4 horas,"1250,5","R$ 3.890,00",ENTREGUE - sem ocorrências
1,E-002,TECH STORE ME,"[Rio de Janeiro, RJ, Belo Horizonte, MG]",2024/04/02,05-04-2024,2 dias e 18 horas,"780,0","R$ 2.150,75",ENTREGUE - com atraso de 6h
2,E-003,Distribuidora Nordeste S.A.,"[Recife, PE, Salvador, BA]",28/04/2024,2024-05-01,2 dias e 12 horas,"2100,8","R$ 5.420,00",ENTREGUE - sem ocorrências
3,E-004,AUTO PEÇAS REGIONAL LTDA,"[Manaus, AM, Belém, PA]",2024/05/10,15-05-2024,4 dias e 22 horas,"3500,0","R$ 12.750,30",ENTREGUE - com avaria parcial
4,E-005,pharma express distribuidora,"[Curitiba, PR, Florianópolis, SC]",20/06/2024,2024-06-21,1 dia e 8 horas,"420,3","R$ 1.280,00",ENTREGUE - sem ocorrências
5,E-006,MEGA ATACADO EIRELI,"[Porto Alegre, RS, São Paulo, SP]",2024/07/15,19-07-2024,3 dias e 16 horas,"1890,0","R$ 4.670,50",ENTREGUE - com atraso de 12h
6,E-007,Casa & Construção Materiais,"[Brasília, DF, Goiânia, GO]",01/08/2024,2024-08-02,1 dia e 14 horas,"960,7","R$ 1.950,00",ENTREGUE - sem ocorrências

In [214]:
relatorio_operacional_logistica[['cidade_origem', 'uf_origem', 'cidade_destino', 'uf_destino']] = pd.DataFrame(relatorio_operacional_logistica['rota'].to_list(), index=relatorio_operacional_logistica.index)

In [215]:
relatorio_operacional_logistica

,id_entrega,cliente,rota,data_pedido,data_entrega,tempo_transporte,peso_kg,valor_frete,status_entrega,cidade_origem,uf_origem,cidade_destino,uf_destino
0,E-001,MAGAZINE CENTRAL LTDA,"[São Paulo, SP, Curitiba, PR]",15/03/2024,2024-03-18,3 dias e 4 horas,"1250,5","R$ 3.890,00",ENTREGUE - sem ocorrências,São Paulo,SP,Curitiba,PR
1,E-002,TECH STORE ME,"[Rio de Janeiro, RJ, Belo Horizonte, MG]",2024/04/02,05-04-2024,2 dias e 18 horas,"780,0","R$ 2.150,75",ENTREGUE - com atraso de 6h,Rio de Janeiro,RJ,Belo Horizonte,MG
2,E-003,Distribuidora Nordeste S.A.,"[Recife, PE, Salvador, BA]",28/04/2024,2024-05-01,2 dias e 12 horas,"2100,8","R$ 5.420,00",ENTREGUE - sem ocorrências,Recife,PE,Salvador,BA
3,E-004,AUTO PEÇAS REGIONAL LTDA,"[Manaus, AM, Belém, PA]",2024/05/10,15-05-2024,4 dias e 22 horas,"3500,0","R$ 12.750,30",ENTREGUE - com avaria parcial,Manaus,AM,Belém,PA
4,E-005,pharma express distribuidora,"[Curitiba, PR, Florianópolis, SC]",20/06/2024,2024-06-21,1 dia e 8 horas,"420,3","R$ 1.280,00",ENTREGUE - sem ocorrências,Curitiba,PR,Florianópolis,SC
5,E-006,MEGA ATACADO EIRELI,"[Porto Alegre, RS, São Paulo, SP]",2024/07/15,19-07-2024,3 dias e 16 horas,"1890,0","R$ 4.670,50",ENTREGUE - com atraso de 12h,Porto Alegre,RS,São Paulo,SP
6,E-007,Casa & Construção Materiais,"[Brasília, DF, Goiânia, GO]",01/08/2024,2024-08-02,1 dia e 14 horas,"960,7","R$ 1.950,00",ENTREGUE - sem ocorrências,Brasília,DF,Goiânia,GO

In [216]:
relatorio_operacional_logistica = relatorio_operacional_logistica.drop(columns='rota')

In [217]:
relatorio_operacional_logistica

,id_entrega,cliente,data_pedido,data_entrega,tempo_transporte,peso_kg,valor_frete,status_entrega,cidade_origem,uf_origem,cidade_destino,uf_destino
0,E-001,MAGAZINE CENTRAL LTDA,15/03/2024,2024-03-18,3 dias e 4 horas,"1250,5","R$ 3.890,00",ENTREGUE - sem ocorrências,São Paulo,SP,Curitiba,PR
1,E-002,TECH STORE ME,2024/04/02,05-04-2024,2 dias e 18 horas,"780,0","R$ 2.150,75",ENTREGUE - com atraso de 6h,Rio de Janeiro,RJ,Belo Horizonte,MG
2,E-003,Distribuidora Nordeste S.A.,28/04/2024,2024-05-01,2 dias e 12 horas,"2100,8","R$ 5.420,00",ENTREGUE - sem ocorrências,Recife,PE,Salvador,BA
3,E-004,AUTO PEÇAS REGIONAL LTDA,2024/05/10,15-05-2024,4 dias e 22 horas,"3500,0","R$ 12.750,30",ENTREGUE - com avaria parcial,Manaus,AM,Belém,PA
4,E-005,pharma express distribuidora,20/06/2024,2024-06-21,1 dia e 8 horas,"420,3","R$ 1.280,00",ENTREGUE - sem ocorrências,Curitiba,PR,Florianópolis,SC
5,E-006,MEGA ATACADO EIRELI,2024/07/15,19-07-2024,3 dias e 16 horas,"1890,0","R$ 4.670,50",ENTREGUE - com atraso de 12h,Porto Alegre,RS,São Paulo,SP
6,E-007,Casa & Construção Materiais,01/08/2024,2024-08-02,1 dia e 14 horas,"960,7","R$ 1.950,00",ENTREGUE - sem ocorrências,Brasília,DF,Goiânia,GO

### Formatação das colunas 'data_pedido' e 'data_entrega'

In [218]:
relatorio_operacional_logistica.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_entrega        7 non-null      str
 1   cliente           7 non-null      str
 2   data_pedido       7 non-null      str
 3   data_entrega      7 non-null      str
 4   tempo_transporte  7 non-null      str
 5   peso_kg           7 non-null      str
 6   valor_frete       7 non-null      str
 7   status_entrega    7 non-null      str
 8   cidade_origem     7 non-null      str
 9   uf_origem         7 non-null      str
 10  cidade_destino    7 non-null      str
 11  uf_destino        7 non-null      str
dtypes: str(12)
memory usage: 804.0 bytes

In [219]:
relatorio_operacional_logistica[['data_pedido']]

  data_pedido
0  15/03/2024
1  2024/04/02
2  28/04/2024
3  2024/05/10
4  20/06/2024
5  2024/07/15
6  01/08/2024

In [220]:
datas_iso = pd.to_datetime(relatorio_operacional_logistica['data_pedido'], format='%Y/%m/%d', errors='coerce')
datas_br = pd.to_datetime(relatorio_operacional_logistica['data_pedido'], format='%d/%m/%Y', errors='coerce')
relatorio_operacional_logistica['data_pedido'] = datas_iso.fillna(datas_br)

In [221]:
relatorio_operacional_logistica[['data_pedido']]

  data_pedido
0  2024-03-15
1  2024-04-02
2  2024-04-28
3  2024-05-10
4  2024-06-20
5  2024-07-15
6  2024-08-01

In [222]:
relatorio_operacional_logistica[['data_entrega']]

  data_entrega
0   2024-03-18
1   05-04-2024
2   2024-05-01
3   15-05-2024
4   2024-06-21
5   19-07-2024
6   2024-08-02

In [223]:
datas_iso = pd.to_datetime(relatorio_operacional_logistica['data_entrega'], format='%Y-%m-%d', errors='coerce')

In [224]:
datas_iso

0   2024-03-18
1          NaT
2   2024-05-01
3          NaT
4   2024-06-21
5          NaT
6   2024-08-02
Name: data_entrega, dtype: datetime64[us]

In [225]:
datas_br = pd.to_datetime(relatorio_operacional_logistica['data_entrega'], format='%d-%m-%Y', errors='coerce')

In [226]:
datas_br

0          NaT
1   2024-04-05
2          NaT
3   2024-05-15
4          NaT
5   2024-07-19
6          NaT
Name: data_entrega, dtype: datetime64[us]

In [227]:
relatorio_operacional_logistica['data_entrega'] = datas_iso.fillna(datas_br)

In [228]:
relatorio_operacional_logistica[['data_pedido', 'data_entrega']]

  data_pedido data_entrega
0  2024-03-15   2024-03-18
1  2024-04-02   2024-04-05
2  2024-04-28   2024-05-01
3  2024-05-10   2024-05-15
4  2024-06-20   2024-06-21
5  2024-07-15   2024-07-19
6  2024-08-01   2024-08-02

In [229]:
relatorio_operacional_logistica.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_entrega        7 non-null      str
 1   cliente           7 non-null      str
 2   data_pedido       7 non-null      datetime64[us]
 3   data_entrega      7 non-null      datetime64[us]
 4   tempo_transporte  7 non-null      str
 5   peso_kg           7 non-null      str
 6   valor_frete       7 non-null      str
 7   status_entrega    7 non-null      str
 8   cidade_origem     7 non-null      str
 9   uf_origem         7 non-null      str
 10  cidade_destino    7 non-null      str
 11  uf_destino        7 non-null      str
dtypes: datetime64[us](2), str(10)
memory usage: 804.0 bytes

In [230]:
relatorio_operacional_logistica

,id_entrega,cliente,data_pedido,data_entrega,tempo_transporte,peso_kg,valor_frete,status_entrega,cidade_origem,uf_origem,cidade_destino,uf_destino
0,E-001,MAGAZINE CENTRAL LTDA,2024-03-15,2024-03-18,3 dias e 4 horas,"1250,5","R$ 3.890,00",ENTREGUE - sem ocorrências,São Paulo,SP,Curitiba,PR
1,E-002,TECH STORE ME,2024-04-02,2024-04-05,2 dias e 18 horas,"780,0","R$ 2.150,75",ENTREGUE - com atraso de 6h,Rio de Janeiro,RJ,Belo Horizonte,MG
2,E-003,Distribuidora Nordeste S.A.,2024-04-28,2024-05-01,2 dias e 12 horas,"2100,8","R$ 5.420,00",ENTREGUE - sem ocorrências,Recife,PE,Salvador,BA
3,E-004,AUTO PEÇAS REGIONAL LTDA,2024-05-10,2024-05-15,4 dias e 22 horas,"3500,0","R$ 12.750,30",ENTREGUE - com avaria parcial,Manaus,AM,Belém,PA
4,E-005,pharma express distribuidora,2024-06-20,2024-06-21,1 dia e 8 horas,"420,3","R$ 1.280,00",ENTREGUE - sem ocorrências,Curitiba,PR,Florianópolis,SC
5,E-006,MEGA ATACADO EIRELI,2024-07-15,2024-07-19,3 dias e 16 horas,"1890,0","R$ 4.670,50",ENTREGUE - com atraso de 12h,Porto Alegre,RS,São Paulo,SP
6,E-007,Casa & Construção Materiais,2024-08-01,2024-08-02,1 dia e 14 horas,"960,7","R$ 1.950,00",ENTREGUE - sem ocorrências,Brasília,DF,Goiânia,GO

### 4. Transformação da coluna 'tempo_transporte'

In [231]:
relatorio_operacional_logistica['tempo_transporte']

0     3 dias e 4 horas
1    2 dias e 18 horas
2    2 dias e 12 horas
3    4 dias e 22 horas
4      1 dia e 8 horas
5    3 dias e 16 horas
6     1 dia e 14 horas
Name: tempo_transporte, dtype: str

In [232]:
mascara_timedelta = (relatorio_operacional_logistica['tempo_transporte']
 .str.replace(r'dia', 'day', regex=True)
 .str.replace(r'horas', 'hours', regex=True)
 .str.replace(r'e\s+', '', regex=True)
 .str.strip())

In [233]:
mascara_timedelta

0     3 days 4 hours
1    2 days 18 hours
2    2 days 12 hours
3    4 days 22 hours
4      1 day 8 hours
5    3 days 16 hours
6     1 day 14 hours
Name: tempo_transporte, dtype: str

In [234]:
mascara_timedelta = pd.to_timedelta(mascara_timedelta)

In [235]:
mascara_timedelta

0   3 days 04:00:00
1   2 days 18:00:00
2   2 days 12:00:00
3   4 days 22:00:00
4   1 days 08:00:00
5   3 days 16:00:00
6   1 days 14:00:00
Name: tempo_transporte, dtype: timedelta64[us]

In [236]:
relatorio_operacional_logistica.insert(
    5,
    'horas_transporte',
    mascara_timedelta.dt.total_seconds() / 3600
)

In [237]:
relatorio_operacional_logistica

,id_entrega,cliente,data_pedido,data_entrega,tempo_transporte,horas_transporte,peso_kg,valor_frete,status_entrega,cidade_origem,uf_origem,cidade_destino,uf_destino
0,E-001,MAGAZINE CENTRAL LTDA,2024-03-15,2024-03-18,3 dias e 4 horas,76.0,"1250,5","R$ 3.890,00",ENTREGUE - sem ocorrências,São Paulo,SP,Curitiba,PR
1,E-002,TECH STORE ME,2024-04-02,2024-04-05,2 dias e 18 horas,66.0,"780,0","R$ 2.150,75",ENTREGUE - com atraso de 6h,Rio de Janeiro,RJ,Belo Horizonte,MG
2,E-003,Distribuidora Nordeste S.A.,2024-04-28,2024-05-01,2 dias e 12 horas,60.0,"2100,8","R$ 5.420,00",ENTREGUE - sem ocorrências,Recife,PE,Salvador,BA
3,E-004,AUTO PEÇAS REGIONAL LTDA,2024-05-10,2024-05-15,4 dias e 22 horas,118.0,"3500,0","R$ 12.750,30",ENTREGUE - com avaria parcial,Manaus,AM,Belém,PA
4,E-005,pharma express distribuidora,2024-06-20,2024-06-21,1 dia e 8 horas,32.0,"420,3","R$ 1.280,00",ENTREGUE - sem ocorrências,Curitiba,PR,Florianópolis,SC
5,E-006,MEGA ATACADO EIRELI,2024-07-15,2024-07-19,3 dias e 16 horas,88.0,"1890,0","R$ 4.670,50",ENTREGUE - com atraso de 12h,Porto Alegre,RS,São Paulo,SP
6,E-007,Casa & Construção Materiais,2024-08-01,2024-08-02,1 dia e 14 horas,38.0,"960,7","R$ 1.950,00",ENTREGUE - sem ocorrências,Brasília,DF,Goiânia,GO

In [238]:
relatorio_operacional_logistica.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_entrega        7 non-null      str
 1   cliente           7 non-null      str
 2   data_pedido       7 non-null      datetime64[us]
 3   data_entrega      7 non-null      datetime64[us]
 4   tempo_transporte  7 non-null      str
 5   horas_transporte  7 non-null      float64
 6   peso_kg           7 non-null      str
 7   valor_frete       7 non-null      str
 8   status_entrega    7 non-null      str
 9   cidade_origem     7 non-null      str
 10  uf_origem         7 non-null      str
 11  cidade_destino    7 non-null      str
 12  uf_destino        7 non-null      str
dtypes: datetime64[us](2), float64(1), str(10)
memory usage: 860.0 bytes

### Ajustes na coluna 'peso_kg'

In [239]:
relatorio_operacional_logistica['peso_kg']

0    1250,5
1     780,0
2    2100,8
3    3500,0
4     420,3
5    1890,0
6     960,7
Name: peso_kg, dtype: str

In [240]:
relatorio_operacional_logistica['peso_kg'] = (relatorio_operacional_logistica['peso_kg']
 .str.replace(r',', '.', regex=True)
 .str.strip()
 .astype('float64'))

In [241]:
relatorio_operacional_logistica

,id_entrega,cliente,data_pedido,data_entrega,tempo_transporte,horas_transporte,peso_kg,valor_frete,status_entrega,cidade_origem,uf_origem,cidade_destino,uf_destino
0,E-001,MAGAZINE CENTRAL LTDA,2024-03-15,2024-03-18,3 dias e 4 horas,76.0,1250.5,"R$ 3.890,00",ENTREGUE - sem ocorrências,São Paulo,SP,Curitiba,PR
1,E-002,TECH STORE ME,2024-04-02,2024-04-05,2 dias e 18 horas,66.0,780.0,"R$ 2.150,75",ENTREGUE - com atraso de 6h,Rio de Janeiro,RJ,Belo Horizonte,MG
2,E-003,Distribuidora Nordeste S.A.,2024-04-28,2024-05-01,2 dias e 12 horas,60.0,2100.8,"R$ 5.420,00",ENTREGUE - sem ocorrências,Recife,PE,Salvador,BA
3,E-004,AUTO PEÇAS REGIONAL LTDA,2024-05-10,2024-05-15,4 dias e 22 horas,118.0,3500.0,"R$ 12.750,30",ENTREGUE - com avaria parcial,Manaus,AM,Belém,PA
4,E-005,pharma express distribuidora,2024-06-20,2024-06-21,1 dia e 8 horas,32.0,420.3,"R$ 1.280,00",ENTREGUE - sem ocorrências,Curitiba,PR,Florianópolis,SC
5,E-006,MEGA ATACADO EIRELI,2024-07-15,2024-07-19,3 dias e 16 horas,88.0,1890.0,"R$ 4.670,50",ENTREGUE - com atraso de 12h,Porto Alegre,RS,São Paulo,SP
6,E-007,Casa & Construção Materiais,2024-08-01,2024-08-02,1 dia e 14 horas,38.0,960.7,"R$ 1.950,00",ENTREGUE - sem ocorrências,Brasília,DF,Goiânia,GO

In [242]:
relatorio_operacional_logistica.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_entrega        7 non-null      str
 1   cliente           7 non-null      str
 2   data_pedido       7 non-null      datetime64[us]
 3   data_entrega      7 non-null      datetime64[us]
 4   tempo_transporte  7 non-null      str
 5   horas_transporte  7 non-null      float64
 6   peso_kg           7 non-null      float64
 7   valor_frete       7 non-null      str
 8   status_entrega    7 non-null      str
 9   cidade_origem     7 non-null      str
 10  uf_origem         7 non-null      str
 11  cidade_destino    7 non-null      str
 12  uf_destino        7 non-null      str
dtypes: datetime64[us](2), float64(2), str(9)
memory usage: 860.0 bytes

### Formatação da coluna 'valor_frete'

In [243]:
relatorio_operacional_logistica['valor_frete']

0     R$ 3.890,00
1     R$ 2.150,75
2     R$ 5.420,00
3    R$ 12.750,30
4     R$ 1.280,00
5     R$ 4.670,50
6     R$ 1.950,00
Name: valor_frete, dtype: str

In [244]:
relatorio_operacional_logistica['valor_frete'] = (relatorio_operacional_logistica['valor_frete']
 .str.replace(r'R\$\s+', '', regex=True)
 .str.replace(r'\.', '', regex=True)
 .str.replace(r'\,', '.', regex=True)
 .str.strip()
 .astype('float64'))

In [245]:
relatorio_operacional_logistica

,id_entrega,cliente,data_pedido,data_entrega,tempo_transporte,horas_transporte,peso_kg,valor_frete,status_entrega,cidade_origem,uf_origem,cidade_destino,uf_destino
0,E-001,MAGAZINE CENTRAL LTDA,2024-03-15,2024-03-18,3 dias e 4 horas,76.0,1250.5,3890.00,ENTREGUE - sem ocorrências,São Paulo,SP,Curitiba,PR
1,E-002,TECH STORE ME,2024-04-02,2024-04-05,2 dias e 18 horas,66.0,780.0,2150.75,ENTREGUE - com atraso de 6h,Rio de Janeiro,RJ,Belo Horizonte,MG
2,E-003,Distribuidora Nordeste S.A.,2024-04-28,2024-05-01,2 dias e 12 horas,60.0,2100.8,5420.00,ENTREGUE - sem ocorrências,Recife,PE,Salvador,BA
3,E-004,AUTO PEÇAS REGIONAL LTDA,2024-05-10,2024-05-15,4 dias e 22 horas,118.0,3500.0,12750.30,ENTREGUE - com avaria parcial,Manaus,AM,Belém,PA
4,E-005,pharma express distribuidora,2024-06-20,2024-06-21,1 dia e 8 horas,32.0,420.3,1280.00,ENTREGUE - sem ocorrências,Curitiba,PR,Florianópolis,SC
5,E-006,MEGA ATACADO EIRELI,2024-07-15,2024-07-19,3 dias e 16 horas,88.0,1890.0,4670.50,ENTREGUE - com atraso de 12h,Porto Alegre,RS,São Paulo,SP
6,E-007,Casa & Construção Materiais,2024-08-01,2024-08-02,1 dia e 14 horas,38.0,960.7,1950.00,ENTREGUE - sem ocorrências,Brasília,DF,Goiânia,GO

In [246]:
relatorio_operacional_logistica.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_entrega        7 non-null      str
 1   cliente           7 non-null      str
 2   data_pedido       7 non-null      datetime64[us]
 3   data_entrega      7 non-null      datetime64[us]
 4   tempo_transporte  7 non-null      str
 5   horas_transporte  7 non-null      float64
 6   peso_kg           7 non-null      float64
 7   valor_frete       7 non-null      float64
 8   status_entrega    7 non-null      str
 9   cidade_origem     7 non-null      str
 10  uf_origem         7 non-null      str
 11  cidade_destino    7 non-null      str
 12  uf_destino        7 non-null      str
dtypes: datetime64[us](2), float64(3), str(8)
memory usage: 860.0 bytes

### Criar a tabela 'custo_por_hora'

Crie custo_por_hora: valor_frete / horas_transporte, arredondado para 2 casas decimais.

In [247]:
relatorio_operacional_logistica

,id_entrega,cliente,data_pedido,data_entrega,tempo_transporte,horas_transporte,peso_kg,valor_frete,status_entrega,cidade_origem,uf_origem,cidade_destino,uf_destino
0,E-001,MAGAZINE CENTRAL LTDA,2024-03-15,2024-03-18,3 dias e 4 horas,76.0,1250.5,3890.00,ENTREGUE - sem ocorrências,São Paulo,SP,Curitiba,PR
1,E-002,TECH STORE ME,2024-04-02,2024-04-05,2 dias e 18 horas,66.0,780.0,2150.75,ENTREGUE - com atraso de 6h,Rio de Janeiro,RJ,Belo Horizonte,MG
2,E-003,Distribuidora Nordeste S.A.,2024-04-28,2024-05-01,2 dias e 12 horas,60.0,2100.8,5420.00,ENTREGUE - sem ocorrências,Recife,PE,Salvador,BA
3,E-004,AUTO PEÇAS REGIONAL LTDA,2024-05-10,2024-05-15,4 dias e 22 horas,118.0,3500.0,12750.30,ENTREGUE - com avaria parcial,Manaus,AM,Belém,PA
4,E-005,pharma express distribuidora,2024-06-20,2024-06-21,1 dia e 8 horas,32.0,420.3,1280.00,ENTREGUE - sem ocorrências,Curitiba,PR,Florianópolis,SC
5,E-006,MEGA ATACADO EIRELI,2024-07-15,2024-07-19,3 dias e 16 horas,88.0,1890.0,4670.50,ENTREGUE - com atraso de 12h,Porto Alegre,RS,São Paulo,SP
6,E-007,Casa & Construção Materiais,2024-08-01,2024-08-02,1 dia e 14 horas,38.0,960.7,1950.00,ENTREGUE - sem ocorrências,Brasília,DF,Goiânia,GO

In [248]:
relatorio_operacional_logistica['custo_por_hora'] = (relatorio_operacional_logistica['valor_frete'] / relatorio_operacional_logistica['horas_transporte']).round(2)

In [249]:
relatorio_operacional_logistica

,id_entrega,cliente,data_pedido,data_entrega,tempo_transporte,horas_transporte,peso_kg,valor_frete,status_entrega,cidade_origem,uf_origem,cidade_destino,uf_destino,custo_por_hora
0,E-001,MAGAZINE CENTRAL LTDA,2024-03-15,2024-03-18,3 dias e 4 horas,76.0,1250.5,3890.00,ENTREGUE - sem ocorrências,São Paulo,SP,Curitiba,PR,51.18
1,E-002,TECH STORE ME,2024-04-02,2024-04-05,2 dias e 18 horas,66.0,780.0,2150.75,ENTREGUE - com atraso de 6h,Rio de Janeiro,RJ,Belo Horizonte,MG,32.59
2,E-003,Distribuidora Nordeste S.A.,2024-04-28,2024-05-01,2 dias e 12 horas,60.0,2100.8,5420.00,ENTREGUE - sem ocorrências,Recife,PE,Salvador,BA,90.33
3,E-004,AUTO PEÇAS REGIONAL LTDA,2024-05-10,2024-05-15,4 dias e 22 horas,118.0,3500.0,12750.30,ENTREGUE - com avaria parcial,Manaus,AM,Belém,PA,108.05
4,E-005,pharma express distribuidora,2024-06-20,2024-06-21,1 dia e 8 horas,32.0,420.3,1280.00,ENTREGUE - sem ocorrências,Curitiba,PR,Florianópolis,SC,40.00
5,E-006,MEGA ATACADO EIRELI,2024-07-15,2024-07-19,3 dias e 16 horas,88.0,1890.0,4670.50,ENTREGUE - com atraso de 12h,Porto Alegre,RS,São Paulo,SP,53.07
6,E-007,Casa & Construção Materiais,2024-08-01,2024-08-02,1 dia e 14 horas,38.0,960.7,1950.00,ENTREGUE - sem ocorrências,Brasília,DF,Goiânia,GO,51.32

In [250]:
relatorio_operacional_logistica.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_entrega        7 non-null      str
 1   cliente           7 non-null      str
 2   data_pedido       7 non-null      datetime64[us]
 3   data_entrega      7 non-null      datetime64[us]
 4   tempo_transporte  7 non-null      str
 5   horas_transporte  7 non-null      float64
 6   peso_kg           7 non-null      float64
 7   valor_frete       7 non-null      float64
 8   status_entrega    7 non-null      str
 9   cidade_origem     7 non-null      str
 10  uf_origem         7 non-null      str
 11  cidade_destino    7 non-null      str
 12  uf_destino        7 non-null      str
 13  custo_por_hora    7 non-null      float64
dtypes: datetime64[us](2), float64(4), str(8)
memory usage: 916.0 bytes

### Criar a coluna 'prazo_dias'

Crie prazo_dias: diferença em dias entre data_entrega e data_pedido (como int).

In [251]:
relatorio_operacional_logistica

,id_entrega,cliente,data_pedido,data_entrega,tempo_transporte,horas_transporte,peso_kg,valor_frete,status_entrega,cidade_origem,uf_origem,cidade_destino,uf_destino,custo_por_hora
0,E-001,MAGAZINE CENTRAL LTDA,2024-03-15,2024-03-18,3 dias e 4 horas,76.0,1250.5,3890.00,ENTREGUE - sem ocorrências,São Paulo,SP,Curitiba,PR,51.18
1,E-002,TECH STORE ME,2024-04-02,2024-04-05,2 dias e 18 horas,66.0,780.0,2150.75,ENTREGUE - com atraso de 6h,Rio de Janeiro,RJ,Belo Horizonte,MG,32.59
2,E-003,Distribuidora Nordeste S.A.,2024-04-28,2024-05-01,2 dias e 12 horas,60.0,2100.8,5420.00,ENTREGUE - sem ocorrências,Recife,PE,Salvador,BA,90.33
3,E-004,AUTO PEÇAS REGIONAL LTDA,2024-05-10,2024-05-15,4 dias e 22 horas,118.0,3500.0,12750.30,ENTREGUE - com avaria parcial,Manaus,AM,Belém,PA,108.05
4,E-005,pharma express distribuidora,2024-06-20,2024-06-21,1 dia e 8 horas,32.0,420.3,1280.00,ENTREGUE - sem ocorrências,Curitiba,PR,Florianópolis,SC,40.00
5,E-006,MEGA ATACADO EIRELI,2024-07-15,2024-07-19,3 dias e 16 horas,88.0,1890.0,4670.50,ENTREGUE - com atraso de 12h,Porto Alegre,RS,São Paulo,SP,53.07
6,E-007,Casa & Construção Materiais,2024-08-01,2024-08-02,1 dia e 14 horas,38.0,960.7,1950.00,ENTREGUE - sem ocorrências,Brasília,DF,Goiânia,GO,51.32

In [252]:
relatorio_operacional_logistica.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_entrega        7 non-null      str
 1   cliente           7 non-null      str
 2   data_pedido       7 non-null      datetime64[us]
 3   data_entrega      7 non-null      datetime64[us]
 4   tempo_transporte  7 non-null      str
 5   horas_transporte  7 non-null      float64
 6   peso_kg           7 non-null      float64
 7   valor_frete       7 non-null      float64
 8   status_entrega    7 non-null      str
 9   cidade_origem     7 non-null      str
 10  uf_origem         7 non-null      str
 11  cidade_destino    7 non-null      str
 12  uf_destino        7 non-null      str
 13  custo_por_hora    7 non-null      float64
dtypes: datetime64[us](2), float64(4), str(8)
memory usage: 916.0 bytes

In [253]:
relatorio_operacional_logistica.insert(
    4,
    'prazo_dias',
    (relatorio_operacional_logistica['data_entrega'] - relatorio_operacional_logistica['data_pedido']).dt.days
)

In [254]:
relatorio_operacional_logistica

,id_entrega,cliente,data_pedido,data_entrega,prazo_dias,tempo_transporte,horas_transporte,peso_kg,valor_frete,status_entrega,cidade_origem,uf_origem,cidade_destino,uf_destino,custo_por_hora
0,E-001,MAGAZINE CENTRAL LTDA,2024-03-15,2024-03-18,3,3 dias e 4 horas,76.0,1250.5,3890.00,ENTREGUE - sem ocorrências,São Paulo,SP,Curitiba,PR,51.18
1,E-002,TECH STORE ME,2024-04-02,2024-04-05,3,2 dias e 18 horas,66.0,780.0,2150.75,ENTREGUE - com atraso de 6h,Rio de Janeiro,RJ,Belo Horizonte,MG,32.59
2,E-003,Distribuidora Nordeste S.A.,2024-04-28,2024-05-01,3,2 dias e 12 horas,60.0,2100.8,5420.00,ENTREGUE - sem ocorrências,Recife,PE,Salvador,BA,90.33
3,E-004,AUTO PEÇAS REGIONAL LTDA,2024-05-10,2024-05-15,5,4 dias e 22 horas,118.0,3500.0,12750.30,ENTREGUE - com avaria parcial,Manaus,AM,Belém,PA,108.05
4,E-005,pharma express distribuidora,2024-06-20,2024-06-21,1,1 dia e 8 horas,32.0,420.3,1280.00,ENTREGUE - sem ocorrências,Curitiba,PR,Florianópolis,SC,40.00
5,E-006,MEGA ATACADO EIRELI,2024-07-15,2024-07-19,4,3 dias e 16 horas,88.0,1890.0,4670.50,ENTREGUE - com atraso de 12h,Porto Alegre,RS,São Paulo,SP,53.07
6,E-007,Casa & Construção Materiais,2024-08-01,2024-08-02,1,1 dia e 14 horas,38.0,960.7,1950.00,ENTREGUE - sem ocorrências,Brasília,DF,Goiânia,GO,51.32

In [255]:
relatorio_operacional_logistica.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_entrega        7 non-null      str
 1   cliente           7 non-null      str
 2   data_pedido       7 non-null      datetime64[us]
 3   data_entrega      7 non-null      datetime64[us]
 4   prazo_dias        7 non-null      int64
 5   tempo_transporte  7 non-null      str
 6   horas_transporte  7 non-null      float64
 7   peso_kg           7 non-null      float64
 8   valor_frete       7 non-null      float64
 9   status_entrega    7 non-null      str
 10  cidade_origem     7 non-null      str
 11  uf_origem         7 non-null      str
 12  cidade_destino    7 non-null      str
 13  uf_destino        7 non-null      str
 14  custo_por_hora    7 non-null      float64
dtypes: datetime64[us](2), float64(4), int64(1), str(8)
memory usage: 972.0 bytes

### Formatação da coluna 'status_entrega'

status_entrega: extraia duas novas colunas — entregue (booleano, sempre True nesse dataset mas trate como se pudesse ser False) e ocorrencia (o texto após o " - ", limpo e em minúsculas). Remova a coluna original.

In [256]:
relatorio_operacional_logistica['status_entrega']

0       ENTREGUE - sem ocorrências
1      ENTREGUE - com atraso de 6h
2       ENTREGUE - sem ocorrências
3    ENTREGUE - com avaria parcial
4       ENTREGUE - sem ocorrências
5     ENTREGUE - com atraso de 12h
6       ENTREGUE - sem ocorrências
Name: status_entrega, dtype: str

In [257]:
relatorio_operacional_logistica['entregue'] = relatorio_operacional_logistica['status_entrega'].str.contains('ENTREGUE', case=False, na=False)

In [258]:
relatorio_operacional_logistica

,id_entrega,cliente,data_pedido,data_entrega,prazo_dias,tempo_transporte,horas_transporte,peso_kg,valor_frete,status_entrega,cidade_origem,uf_origem,cidade_destino,uf_destino,custo_por_hora,entregue
0,E-001,MAGAZINE CENTRAL LTDA,2024-03-15,2024-03-18,3,3 dias e 4 horas,76.0,1250.5,3890.00,ENTREGUE - sem ocorrências,São Paulo,SP,Curitiba,PR,51.18,True
1,E-002,TECH STORE ME,2024-04-02,2024-04-05,3,2 dias e 18 horas,66.0,780.0,2150.75,ENTREGUE - com atraso de 6h,Rio de Janeiro,RJ,Belo Horizonte,MG,32.59,True
2,E-003,Distribuidora Nordeste S.A.,2024-04-28,2024-05-01,3,2 dias e 12 horas,60.0,2100.8,5420.00,ENTREGUE - sem ocorrências,Recife,PE,Salvador,BA,90.33,True
3,E-004,AUTO PEÇAS REGIONAL LTDA,2024-05-10,2024-05-15,5,4 dias e 22 horas,118.0,3500.0,12750.30,ENTREGUE - com avaria parcial,Manaus,AM,Belém,PA,108.05,True
4,E-005,pharma express distribuidora,2024-06-20,2024-06-21,1,1 dia e 8 horas,32.0,420.3,1280.00,ENTREGUE - sem ocorrências,Curitiba,PR,Florianópolis,SC,40.00,True
5,E-006,MEGA ATACADO EIRELI,2024-07-15,2024-07-19,4,3 dias e 16 horas,88.0,1890.0,4670.50,ENTREGUE - com atraso de 12h,Porto Alegre,RS,São Paulo,SP,53.07,True
6,E-007,Casa & Construção Materiais,2024-08-01,2024-08-02,1,1 dia e 14 horas,38.0,960.7,1950.00,ENTREGUE - sem ocorrências,Brasília,DF,Goiânia,GO,51.32,True

In [259]:
relatorio_operacional_logistica['ocorrencia'] = (relatorio_operacional_logistica['status_entrega']
 .str.replace(r'.*?- ', '', regex=True)
 .str.strip()
 .str.lower())

In [260]:
relatorio_operacional_logistica

,id_entrega,cliente,data_pedido,data_entrega,prazo_dias,tempo_transporte,horas_transporte,peso_kg,valor_frete,status_entrega,cidade_origem,uf_origem,cidade_destino,uf_destino,custo_por_hora,entregue,ocorrencia
0,E-001,MAGAZINE CENTRAL LTDA,2024-03-15,2024-03-18,3,3 dias e 4 horas,76.0,1250.5,3890.00,ENTREGUE - sem ocorrências,São Paulo,SP,Curitiba,PR,51.18,True,sem ocorrências
1,E-002,TECH STORE ME,2024-04-02,2024-04-05,3,2 dias e 18 horas,66.0,780.0,2150.75,ENTREGUE - com atraso de 6h,Rio de Janeiro,RJ,Belo Horizonte,MG,32.59,True,com atraso de 6h
2,E-003,Distribuidora Nordeste S.A.,2024-04-28,2024-05-01,3,2 dias e 12 horas,60.0,2100.8,5420.00,ENTREGUE - sem ocorrências,Recife,PE,Salvador,BA,90.33,True,sem ocorrências
3,E-004,AUTO PEÇAS REGIONAL LTDA,2024-05-10,2024-05-15,5,4 dias e 22 horas,118.0,3500.0,12750.30,ENTREGUE - com avaria parcial,Manaus,AM,Belém,PA,108.05,True,com avaria parcial
4,E-005,pharma express distribuidora,2024-06-20,2024-06-21,1,1 dia e 8 horas,32.0,420.3,1280.00,ENTREGUE - sem ocorrências,Curitiba,PR,Florianópolis,SC,40.00,True,sem ocorrências
5,E-006,MEGA ATACADO EIRELI,2024-07-15,2024-07-19,4,3 dias e 16 horas,88.0,1890.0,4670.50,ENTREGUE - com atraso de 12h,Porto Alegre,RS,São Paulo,SP,53.07,True,com atraso de 12h
6,E-007,Casa & Construção Materiais,2024-08-01,2024-08-02,1,1 dia e 14 horas,38.0,960.7,1950.00,ENTREGUE - sem ocorrências,Brasília,DF,Goiânia,GO,51.32,True,sem ocorrências

In [261]:
relatorio_operacional_logistica = relatorio_operacional_logistica.drop(columns='status_entrega')

In [262]:
relatorio_operacional_logistica

,id_entrega,cliente,data_pedido,data_entrega,prazo_dias,tempo_transporte,horas_transporte,peso_kg,valor_frete,cidade_origem,uf_origem,cidade_destino,uf_destino,custo_por_hora,entregue,ocorrencia
0,E-001,MAGAZINE CENTRAL LTDA,2024-03-15,2024-03-18,3,3 dias e 4 horas,76.0,1250.5,3890.00,São Paulo,SP,Curitiba,PR,51.18,True,sem ocorrências
1,E-002,TECH STORE ME,2024-04-02,2024-04-05,3,2 dias e 18 horas,66.0,780.0,2150.75,Rio de Janeiro,RJ,Belo Horizonte,MG,32.59,True,com atraso de 6h
2,E-003,Distribuidora Nordeste S.A.,2024-04-28,2024-05-01,3,2 dias e 12 horas,60.0,2100.8,5420.00,Recife,PE,Salvador,BA,90.33,True,sem ocorrências
3,E-004,AUTO PEÇAS REGIONAL LTDA,2024-05-10,2024-05-15,5,4 dias e 22 horas,118.0,3500.0,12750.30,Manaus,AM,Belém,PA,108.05,True,com avaria parcial
4,E-005,pharma express distribuidora,2024-06-20,2024-06-21,1,1 dia e 8 horas,32.0,420.3,1280.00,Curitiba,PR,Florianópolis,SC,40.00,True,sem ocorrências
5,E-006,MEGA ATACADO EIRELI,2024-07-15,2024-07-19,4,3 dias e 16 horas,88.0,1890.0,4670.50,Porto Alegre,RS,São Paulo,SP,53.07,True,com atraso de 12h
6,E-007,Casa & Construção Materiais,2024-08-01,2024-08-02,1,1 dia e 14 horas,38.0,960.7,1950.00,Brasília,DF,Goiânia,GO,51.32,True,sem ocorrências

### Criar CSV final

In [263]:
relatorio_operacional_logistica.to_csv('entregas_padronizado.csv', sep=';', index=False, encoding='utf-8')