In [750]:
import pandas as pd
import numpy as np
import re

In [751]:
pd.set_option('display.max_colwidth', None)

In [752]:
dados = pd.read_csv('cadastro_pj_legado.csv', sep=';', encoding='utf-8')

In [753]:
dados['razao_social'] = (dados['razao_social']
                         .str.replace(r"\s+", " ", regex=True)
                         .str.strip()
                         .str.title()
                         .str.replace(r"ltda\.?", "LTDA", flags=re.IGNORECASE, regex=True)
                         .str.replace(r"s\.?a\.?", "S.A.", flags=re.IGNORECASE, regex=True)
                         .str.replace(r"\bme\b", "ME", flags=re.IGNORECASE, regex=True))

In [754]:
dados['razao_social']

0                   Tech Solutions LTDA
1                     Green Energy S.A.
2    Alfa & Beta Consultores Associados
3      Indústria Metalúrgica Norte LTDA
4             Pharma Vida Distribuidora
Name: razao_social, dtype: str

In [755]:
dados['cnpj']

0    12.345.678/0001-90
1        98765432000155
2    11.222.333/0001-44
3    55.666.777/0001-88
4      33444555000199
Name: cnpj, dtype: str

In [756]:
dados['cnpj'] = (dados['cnpj']
                 .str.replace(r"\D", "", regex=True))

In [757]:
dados['cnpj']

0    12345678000190
1    98765432000155
2    11222333000144
3    55666777000188
4    33444555000199
Name: cnpj, dtype: str

In [758]:
padrao_cnpj = r'(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})'
mascara_cnpj = r'\1.\2.\3/\4-\5'

In [759]:
dados['cnpj'] = (dados['cnpj']
                 .str.replace(padrao_cnpj, mascara_cnpj, regex=True))

In [760]:
dados['cnpj']

0    12.345.678/0001-90
1    98.765.432/0001-55
2    11.222.333/0001-44
3    55.666.777/0001-88
4    33.444.555/0001-99
Name: cnpj, dtype: str

In [761]:
dados

,id_cliente,razao_social,cnpj,endereco_completo,email_contato,tags_servico,valor_contrato_mensal
0,C-001,Tech Solutions LTDA,12.345.678/0001-90,"Rua das Flores, 123 - Sala 45 - Centro - São Paulo - SP - 01234-567",CONTATO@techsolutions.COM.BR,"consultoria, implantação/ suporte","R$ 15.750,00"
1,C-002,Green Energy S.A.,98.765.432/0001-55,"Av. Brasil, 4500 - Bloco B - Asa Norte - Brasília - DF - 70000-000",vendas@greenenergy.com.br,energia solar/ manutenção; projetos,"R$ 42.000,00"
2,C-003,Alfa & Beta Consultores Associados,11.222.333/0001-44,"Travessa do Comércio, 78 - Sala 12 - Recife Antigo - Recife - PE - 50030-210",alfa.beta@consultores.com.br,"auditoria, compliance/consultoria tributária","R$ 8.900,00"
3,C-004,Indústria Metalúrgica Norte LTDA,55.666.777/0001-88,"Rod. BR-101, Km 42 - Galpão 7 - Distrito Industrial - Manaus - AM - 69075-000",financeiro@METALURGICA-NORTE.com.br,"usinagem; soldagem /montagem industrial, logística","R$ 127.300,00"
4,C-005,Pharma Vida Distribuidora,33.444.555/0001-99,"Rua Sete de Setembro, 2200 - Andar 8 - Centro - Curitiba - PR - 80060-070",contato@pharmavida.com.br,"distribuição, armazenagem/ logística farmacêutica","R$ 63.450,00"

In [762]:
dados['endereco_completo']

0              Rua das Flores, 123 - Sala 45 - Centro - São Paulo - SP - 01234-567
1               Av. Brasil, 4500 - Bloco B - Asa Norte - Brasília - DF - 70000-000
2     Travessa do Comércio, 78 - Sala 12 - Recife Antigo - Recife - PE - 50030-210
3    Rod. BR-101, Km 42 - Galpão 7 - Distrito Industrial - Manaus - AM - 69075-000
4        Rua Sete de Setembro, 2200 - Andar 8 - Centro - Curitiba - PR - 80060-070
Name: endereco_completo, dtype: str

In [763]:
dados['endereco_completo'] = (dados['endereco_completo']
 .str.split(r'(?<![a-zA-Z0-9])-|-(?![a-zA-Z0-9])'))

In [764]:
dados

,id_cliente,razao_social,cnpj,endereco_completo,email_contato,tags_servico,valor_contrato_mensal
0,C-001,Tech Solutions LTDA,12.345.678/0001-90,"[Rua das Flores, 123 , Sala 45 , Centro , São Paulo , SP , 01234-567]",CONTATO@techsolutions.COM.BR,"consultoria, implantação/ suporte","R$ 15.750,00"
1,C-002,Green Energy S.A.,98.765.432/0001-55,"[Av. Brasil, 4500 , Bloco B , Asa Norte , Brasília , DF , 70000-000]",vendas@greenenergy.com.br,energia solar/ manutenção; projetos,"R$ 42.000,00"
2,C-003,Alfa & Beta Consultores Associados,11.222.333/0001-44,"[Travessa do Comércio, 78 , Sala 12 , Recife Antigo , Recife , PE , 50030-210]",alfa.beta@consultores.com.br,"auditoria, compliance/consultoria tributária","R$ 8.900,00"
3,C-004,Indústria Metalúrgica Norte LTDA,55.666.777/0001-88,"[Rod. BR-101, Km 42 , Galpão 7 , Distrito Industrial , Manaus , AM , 69075-000]",financeiro@METALURGICA-NORTE.com.br,"usinagem; soldagem /montagem industrial, logística","R$ 127.300,00"
4,C-005,Pharma Vida Distribuidora,33.444.555/0001-99,"[Rua Sete de Setembro, 2200 , Andar 8 , Centro , Curitiba , PR , 80060-070]",contato@pharmavida.com.br,"distribuição, armazenagem/ logística farmacêutica","R$ 63.450,00"

In [765]:
dados[['logradouro', 'complemento', 'bairro', 'cidade', 'uf', 'cep']] = pd.DataFrame(dados['endereco_completo'].to_list())
dados[['logradouro', 'complemento', 'bairro', 'cidade', 'uf', 'cep']] = dados[['logradouro', 'complemento', 'bairro', 'cidade', 'uf', 'cep']].apply(lambda x: x.str.strip())

In [766]:
dados[['logradouro', 'complemento', 'bairro', 'cidade', 'uf', 'cep']]

,logradouro,complemento,bairro,cidade,uf,cep
0,"Rua das Flores, 123",Sala 45,Centro,São Paulo,SP,01234-567
1,"Av. Brasil, 4500",Bloco B,Asa Norte,Brasília,DF,70000-000
2,"Travessa do Comércio, 78",Sala 12,Recife Antigo,Recife,PE,50030-210
3,"Rod. BR-101, Km 42",Galpão 7,Distrito Industrial,Manaus,AM,69075-000
4,"Rua Sete de Setembro, 2200",Andar 8,Centro,Curitiba,PR,80060-070

In [767]:
dados = dados.drop(columns='endereco_completo')

In [768]:
dados

,id_cliente,razao_social,cnpj,email_contato,tags_servico,valor_contrato_mensal,logradouro,complemento,bairro,cidade,uf,cep
0,C-001,Tech Solutions LTDA,12.345.678/0001-90,CONTATO@techsolutions.COM.BR,"consultoria, implantação/ suporte","R$ 15.750,00","Rua das Flores, 123",Sala 45,Centro,São Paulo,SP,01234-567
1,C-002,Green Energy S.A.,98.765.432/0001-55,vendas@greenenergy.com.br,energia solar/ manutenção; projetos,"R$ 42.000,00","Av. Brasil, 4500",Bloco B,Asa Norte,Brasília,DF,70000-000
2,C-003,Alfa & Beta Consultores Associados,11.222.333/0001-44,alfa.beta@consultores.com.br,"auditoria, compliance/consultoria tributária","R$ 8.900,00","Travessa do Comércio, 78",Sala 12,Recife Antigo,Recife,PE,50030-210
3,C-004,Indústria Metalúrgica Norte LTDA,55.666.777/0001-88,financeiro@METALURGICA-NORTE.com.br,"usinagem; soldagem /montagem industrial, logística","R$ 127.300,00","Rod. BR-101, Km 42",Galpão 7,Distrito Industrial,Manaus,AM,69075-000
4,C-005,Pharma Vida Distribuidora,33.444.555/0001-99,contato@pharmavida.com.br,"distribuição, armazenagem/ logística farmacêutica","R$ 63.450,00","Rua Sete de Setembro, 2200",Andar 8,Centro,Curitiba,PR,80060-070

In [769]:
dados['email_contato'] = (dados['email_contato']
                          .str.lower())

In [770]:
dados['email_contato']

0           contato@techsolutions.com.br
1              vendas@greenenergy.com.br
2           alfa.beta@consultores.com.br
3    financeiro@metalurgica-norte.com.br
4              contato@pharmavida.com.br
Name: email_contato, dtype: str

In [771]:
condicao = r'^[^@]+@[^@]+\.[^@]+$'

In [772]:
dados.insert(4, 'email_valido', dados['email_contato'].str.fullmatch(condicao))

In [773]:
dados['tags_servico']

0                    consultoria, implantação/ suporte
1                   energia solar/ manutenção; projetos
2          auditoria, compliance/consultoria tributária
3    usinagem; soldagem /montagem industrial, logística
4    distribuição, armazenagem/ logística farmacêutica
Name: tags_servico, dtype: str

In [774]:
dados['tags_servico'] = (dados['tags_servico']
 .str.replace(r'[/;]', ',', regex=True)
 .str.strip()
 .str.split(',')
 )

In [775]:
dados['tags_servico']

0                      [consultoria,  implantação,  suporte]
1                    [energia solar,  manutenção,  projetos]
2           [auditoria,  compliance, consultoria tributária]
3    [usinagem,  soldagem , montagem industrial,  logística]
4      [distribuição,  armazenagem,  logística farmacêutica]
Name: tags_servico, dtype: object

In [776]:
dados['tags_servico'] = (dados['tags_servico']
 .str.join('|')
 .str.replace(r'\s*\|\s*', '|', regex=True))

In [777]:
dados

,id_cliente,razao_social,cnpj,email_contato,email_valido,tags_servico,valor_contrato_mensal,logradouro,complemento,bairro,cidade,uf,cep
0,C-001,Tech Solutions LTDA,12.345.678/0001-90,contato@techsolutions.com.br,True,consultoria|implantação|suporte,"R$ 15.750,00","Rua das Flores, 123",Sala 45,Centro,São Paulo,SP,01234-567
1,C-002,Green Energy S.A.,98.765.432/0001-55,vendas@greenenergy.com.br,True,energia solar|manutenção|projetos,"R$ 42.000,00","Av. Brasil, 4500",Bloco B,Asa Norte,Brasília,DF,70000-000
2,C-003,Alfa & Beta Consultores Associados,11.222.333/0001-44,alfa.beta@consultores.com.br,True,auditoria|compliance|consultoria tributária,"R$ 8.900,00","Travessa do Comércio, 78",Sala 12,Recife Antigo,Recife,PE,50030-210
3,C-004,Indústria Metalúrgica Norte LTDA,55.666.777/0001-88,financeiro@metalurgica-norte.com.br,True,usinagem|soldagem|montagem industrial|logística,"R$ 127.300,00","Rod. BR-101, Km 42",Galpão 7,Distrito Industrial,Manaus,AM,69075-000
4,C-005,Pharma Vida Distribuidora,33.444.555/0001-99,contato@pharmavida.com.br,True,distribuição|armazenagem|logística farmacêutica,"R$ 63.450,00","Rua Sete de Setembro, 2200",Andar 8,Centro,Curitiba,PR,80060-070

In [778]:
dados['valor_contrato_mensal'] = (dados['valor_contrato_mensal']
 .str.replace(r'[R$ \.]', '', regex=True)
 .str.replace(',', '.', regex=True)
 .astype(np.float64))

In [779]:
dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_cliente             5 non-null      str
 1   razao_social           5 non-null      str
 2   cnpj                   5 non-null      str
 3   email_contato          5 non-null      str
 4   email_valido           5 non-null      bool
 5   tags_servico           5 non-null      object
 6   valor_contrato_mensal  5 non-null      float64
 7   logradouro             5 non-null      str
 8   complemento            5 non-null      str
 9   bairro                 5 non-null      str
 10  cidade                 5 non-null      str
 11  uf                     5 non-null      str
 12  cep                    5 non-null      str
dtypes: bool(1), float64(1), object(1), str(10)
memory usage: 617.0+ bytes

In [780]:
dados

,id_cliente,razao_social,cnpj,email_contato,email_valido,tags_servico,valor_contrato_mensal,logradouro,complemento,bairro,cidade,uf,cep
0,C-001,Tech Solutions LTDA,12.345.678/0001-90,contato@techsolutions.com.br,True,consultoria|implantação|suporte,15750.0,"Rua das Flores, 123",Sala 45,Centro,São Paulo,SP,01234-567
1,C-002,Green Energy S.A.,98.765.432/0001-55,vendas@greenenergy.com.br,True,energia solar|manutenção|projetos,42000.0,"Av. Brasil, 4500",Bloco B,Asa Norte,Brasília,DF,70000-000
2,C-003,Alfa & Beta Consultores Associados,11.222.333/0001-44,alfa.beta@consultores.com.br,True,auditoria|compliance|consultoria tributária,8900.0,"Travessa do Comércio, 78",Sala 12,Recife Antigo,Recife,PE,50030-210
3,C-004,Indústria Metalúrgica Norte LTDA,55.666.777/0001-88,financeiro@metalurgica-norte.com.br,True,usinagem|soldagem|montagem industrial|logística,127300.0,"Rod. BR-101, Km 42",Galpão 7,Distrito Industrial,Manaus,AM,69075-000
4,C-005,Pharma Vida Distribuidora,33.444.555/0001-99,contato@pharmavida.com.br,True,distribuição|armazenagem|logística farmacêutica,63450.0,"Rua Sete de Setembro, 2200",Andar 8,Centro,Curitiba,PR,80060-070

In [781]:
dados.to_csv('cadastro_pj_padronizado.csv', sep=';', index=False, encoding='utf-8')